import './globals.css';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';
import Deletrea from './components/texto_animado/page';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alejandro Ponce',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="es">
      
      
      <body><div><h1 className="text-center text-white bg-dark"><Deletrea /></h1> 
      <ul>
  <li> <Link href="/posts/contacto"><h6>Contacto</h6></Link></li>
  <li><Link href="/posts/contador"><h6>Contador</h6></Link></li>
  <li><Link href="/posts/contador_automatico"><h6>Contador Automatico</h6></Link></li>
  <li><Link href="/posts/tictactoe"><h6>Tateti</h6></Link></li>
  <li><Link href="/posts/sobre-mi"><h6>Sobre mi</h6></Link></li>
  </ul>{children}</div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
    </html>
  )
}
